# Generated by Django 4.2.4 on 2023-08-09 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeOfInvestments', models.CharField(max_length=200)),
                ('InstitutionInvestmentHeld', models.CharField(max_length=200)),
                ('DocumentOfOwnership', models.CharField(max_length=200)),
                ('SourceOfFunds', models.CharField(choices=[('Donor_Funds', 'Donor Funds'), ('Development Fund', 'Development Fund')], max_length=200)),
                ('DateOfInvestment', models.DateField()),
                ('MaturityDate', models.DateField()),
                ('DurationOfInvestment', models.IntegerField()),
                ('InterestRate', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Unitcost', models.IntegerField()),
                ('InitialCostOfpurchase', models.IntegerField()),
                ('Expectedinterest', models.IntegerField()),
                ('MaturityValue', models.IntegerField()),
                ('Department', models.CharField(choices=[('CPSB', 'CPSB'), ('REVENUE', 'REVENUE SERVICES')], max_length=200)),
                ('Responsible_officer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
