# Generated by Django 4.2.4 on 2023-08-09 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=200)),
                ('BuildingOwnership', models.CharField(max_length=200)),
                ('Category', models.CharField(choices=[('Building', 'Building'), ('Investment Property', 'Investment Property')], max_length=200)),
                ('BuildingNo', models.CharField(max_length=200)),
                ('InstitutionNo', models.CharField(max_length=200)),
                ('NearestTown', models.CharField(max_length=200)),
                ('Street', models.CharField(max_length=200)),
                ('County', models.CharField(default='Mandera', max_length=200)),
                ('LRNo', models.CharField(max_length=200)),
                ('OwnershipStatus', models.CharField(choices=[('Freehold', 'Freehold'), ('Leasehold', 'Leasehold')], max_length=200)),
                ('SourceOfFunds', models.CharField(choices=[('Donor_Funds', 'Donor Funds'), ('Development Fund', 'Development Fund')], max_length=200)),
                ('ModeOfAcquisition', models.CharField(max_length=200)),
                ('TypeOfBuilding', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=200)),
                ('DesignatedUse', models.CharField(max_length=200)),
                ('EstimatedUsefulLife', models.IntegerField()),
                ('NumberOfFloors', models.IntegerField()),
                ('PlinthArea', models.CharField(max_length=200)),
                ('CostOfConstruction', models.CharField(max_length=200)),
                ('Department', models.CharField(choices=[('CPSB', 'CPSB'), ('REVENUE', 'REVENUE SERVICES')], max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('Remarks', models.TextField(max_length=200)),
                ('Responsible_officer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
