# Generated by Django 4.2.4 on 2023-08-09 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleRegistrationNo', models.CharField(max_length=20)),
                ('EngineNo', models.CharField(max_length=200)),
                ('ChassisNo', models.CharField(max_length=200)),
                ('Financed_By', models.CharField(max_length=200)),
                ('Serial_Number', models.CharField(max_length=200)),
                ('Tag_Number', models.CharField(max_length=200)),
                ('MakeModel', models.CharField(max_length=200)),
                ('Date_of_Delivery', models.DateTimeField(max_length=200)),
                ('PVNumber', models.CharField(max_length=200)),
                ('Original_Location', models.CharField(choices=[('CPSB', 'CPSB'), ('REVENUE', 'REVENUE SERVICES')], max_length=200)),
                ('Current_Location', models.CharField(choices=[('CPSB', 'CPSB'), ('REVENUE', 'REVENUE SERVICES')], max_length=200)),
                ('YearOfPurchase', models.DateField(max_length=200)),
                ('Replacement_Date', models.DateField(blank=True, null=True)),
                ('Purchase_Amount', models.CharField(max_length=200)),
                ('Depreciation_rate', models.IntegerField()),
                ('Annual_depreciation', models.IntegerField()),
                ('Accumulated_depreciation', models.IntegerField()),
                ('DateOfDisposal', models.DateField(max_length=200)),
                ('Disposal_Value', models.IntegerField()),
                ('Department', models.CharField(choices=[('CPSB', 'CPSB'), ('REVENUE', 'REVENUE SERVICES')], max_length=200)),
                ('Assetcondition', models.CharField(max_length=200)),
                ('AssetDescription', models.TextField(max_length=200)),
                ('Notes', models.CharField(max_length=200)),
                ('Responsible_officer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
