# Generated by Django 4.2.4 on 2023-08-09 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_Name', models.CharField(max_length=200)),
                ('Asset_Class', models.CharField(choices=[('ICT_Computer_equipment', 'ICT/Computer Equipment'), ('Furniture', 'Furniture'), ('Fittings', 'Fittings'), ('Plant_Machinery', 'Plant & Machinery'), ('Portable_Attractive', 'Portable and Attractive')], max_length=100)),
                ('Financed_By', models.CharField(max_length=200)),
                ('Serial_Number', models.CharField(max_length=200)),
                ('Tag_Number', models.CharField(max_length=200)),
                ('Make_Model', models.CharField(max_length=200)),
                ('Date_of_Delivery', models.DateTimeField(max_length=200)),
                ('PV_Number', models.CharField(max_length=200)),
                ('Original_Location', models.CharField(choices=[('CPSB', 'CPSB'), ('REVENUE', 'REVENUE SERVICES')], max_length=200)),
                ('Current_Location', models.CharField(choices=[('CPSB', 'CPSB'), ('REVENUE', 'REVENUE SERVICES')], max_length=200)),
                ('Replacement_Date', models.DateTimeField(max_length=200)),
                ('Purchase_Amount', models.CharField(max_length=200)),
                ('Depreciation_rate', models.IntegerField()),
                ('Annual_depreciation', models.IntegerField()),
                ('Date_of_disposal', models.DateField(max_length=200)),
                ('Disposal_value', models.IntegerField()),
                ('Department', models.CharField(choices=[('CPSB', 'CPSB'), ('REVENUE', 'REVENUE SERVICES')], max_length=200)),
                ('Asset_condition', models.CharField(max_length=200)),
                ('Asset_Description', models.TextField(max_length=200)),
                ('Responsible_officer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
